<a href="https://colab.research.google.com/github/ChoiSenn/Study/blob/main/%20data_analysis/ch03_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **고급프로그래밍 - 데이터 분석과 머신러닝**
## 202251509 최세은

<br>


---
<br>


## 3-1. 다음의 기능을 넘파이를 사용하여 구현하시오.

### 1) numpy의 arange() 함수를 사용하여 1에서 45까지의 연속적인 번호를 생성하라.

In [ ]:
import numpy as np  # numpy 라이브러리 사용을 위해 import 한다

a = np.arange(1, 46)  # arange() 함수를 이용하여 1부터 45까지의 연속적인 수열을 가진 배열을 생성
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


*numpy 모듈 사용을 위해 첫 줄에 numpy import를 해준다. 이하 코드에서 np로 사용할 수 있다.<br>
arange() 함수에 인자를 주어 1~46의 연속된 숫자를 배열로 만들고 이를 a 변수에 저장한다.<br>
변수 a를 출력한다.*


---



### 2) 랜덤 시드값을 85로 설정하라. 그리고 이 배열을 랜덤하게 섞어서(shuffle) 첫 6개의 숫자를 슬라이싱 하라. 그 결과를 lotto 변수에 할당한 후, 출력하여라.

In [ ]:
np.random.seed(85)  # seed값을 85로 특정

np.random.shuffle(a)  # shuffle()을 이용하여 a 배열을 랜덤하게 섞는다
lotto = a[:6]  # 첫 6개의 숫자를 슬라이싱
print("lotto =", lotto)

lotto = [ 4 22 23 15  5 11]


*random.seed()를 이용해 시드값을 85로 특정시킨다.<br>
random.shuffle()을 이용해 a 배열을 랜덤하게 섞는다. 이때, random의 시드값은 85이다.<br>
lotto 변수에 a 배열의 6번째까지의 숫자를 슬라이싱하여 저장한다.<br>
lotto 변수를 출력한다.*


---



### 3) lotto 배열을 정렬한 후 출력하고 추가번호를 출력하라. 추가번호는 7번째 숫자를 출력하라.

In [ ]:
print("lotto =", np.sort(lotto), ", 추가번호 =", a[6:7])  # sort()를 이용하여 배열을 정렬

lotto = [ 4  5 11 15 22 23] , 추가번호 = [1]


*sort()를 이용해 lotto 배열을 정렬하고 출력한다.<br> 또한, a 배열의 7번째 숫자를 슬라이싱하여 추가적으로 출력한다.*
___

### 4) 0에서 24까지의 값을 가지는 5 X 5 크기의 2차원 행렬 n_arr를 생성하라.

In [ ]:
n_arr = np.arange(0, 25).reshape(5, 5)  # 0부터 24까지의 값을 가지는 배열을 5 X 5 크기로 생성한다.
print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


*arange() 함수를 이용하여 0부터 24까지의 숫자를 배열로 만들되, reshape() 함수를 이용하여 5 X 5 크기로 생성하여 n_arr 변수에 저장한다.<br>
배열 n_arr를 출력한다.*

---

### 5) 앞서 만든 n_arr의 가장 첫 원소와 가장 마지막 원소를 인덱싱하여 출력하라. 이때, 마지막 원소의 인덱싱은 음수 값을 사용하라.

In [ ]:
print("첫 원소 :", n_arr[:1, :1])  # 우선 :1만큼 슬라이싱 하고 남은 부분에서 :1만큼 슬라이싱 해 첫 원소만을 남긴다
print("마지막 원소 :", n_arr[-1:, -1:])

첫 원소 : [[0]]
마지막 원소 : [[24]]


*n_arr를 우선 :1만큼 슬라이싱하고 남은 부분에서 :1만큼 다시 한 번 슬라이싱 하여 첫 번째 원소 하나만을 출력한다.<br>
n_arr를 우선 -1: 만큼 슬라이싱 하고 남은 부분에서 -1: 만큼 다시 한 번 슬라이싱 하여 마지막 원소 하나만을 출력한다.*

---

### 6) n_arr배열에 슬라이싱을 적용하여 01234, 56789 값을 가지는 배열을 생성하라.

In [ ]:
print(n_arr[:2])  # 행 축에서 :2만큼 슬라이싱하여 출력

[[0 1 2 3 4]
 [5 6 7 8 9]]


*n_arr 배열을 행 축에서 :2 만큼 슬라이스하여 출력한다.*

---

### 7) n_arr 배열에 슬라이싱을 적용하여 특정 배열을 생성하라.

In [ ]:
print(np.hstack((n_arr[:, :1], n_arr[:, 2:3], n_arr[:, 4:5])))  # 각각 열 축으로 슬라이싱한 배열들을 hsrack을 이용해 수평으로 결합

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


*n_arr[:, :1] 만큼 슬라이싱한 배열과 n_arr[:, 2:3]만큼 슬라이싱한 배열과 n_arr[:, 4:5] 만큼 슬라이싱한 배열을(각각 열 축으로 0, 3, 5열만 남겼다) hstack()을 이용하여 수평으로 결합하여 출력한다.*

---

### 8) n_arr 배열에 슬라이싱을 적용한 후, reshape()를 적용하여 특정 배열을 생성하라.

In [ ]:
print(n_arr[:2].reshape(5, 2))  # 슬라이싱한 배열을 reshape()를 이용하여 5행 2열의 배열로 다시 만든다

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


*n_arr[:2] 만큼 슬라이싱한 배열을 reshape()를 이용하여 5행 2열의 배열로 다시 만들어 출력한다.*

---

## 3-2. 난수로 이루어진 2 X 2 X 2 형태의 배열 a를 생성하라.

In [ ]:
a = np.random.randn(2, 2, 2)  # randn()를 이용하여 난수로 이루어진 2 X 2 X 2 배열 생성
a

array([[[ 0.03592585, -0.63066257],
        [ 0.39404568,  1.01710514]],

       [[ 1.91923001,  1.100179  ],
        [-0.7889257 ,  2.58304684]]])

*random.randn()을 이용하여 난수로 이루어진 배열을 생성해 변수 a에 저장한다. 이때, 크기는 인자를 이용해 2 X 2 X 2로 설정한다.<br>
변수 a를 출력한다.*

---

### 1) a 배열에서 max() 메소드를 사용하여 가장 큰 값을 구하여 출력하라.

In [ ]:
print(a.max())  # max()를 이용하여 최대값 출력

2.5830468423246535


*max()를 이용하여 배열 a의 최대값을 출력한다.*

---

### 2) a 배열에서 min() 메소드를 사용하여 가장 작은 값을 구한 다음 출력하라.

In [ ]:
print(a.min())  # min()를 이용하여 최대값 출력

-0.7889256953117791


*min()를 이용하여 배열 a의 최소값을 출력한다.*

---