<a href="https://colab.research.google.com/github/ChoiSenn/Study/blob/main/data_analysis/exercise/ch03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. 파이썬 라이브러리 : 넘파이


## 3-1. 파이썬 리스트와 넘파이

## 3-2. 다차원 배열의 속성들

In [ ]:
import numpy as np

a = np.array([2, 3, 4])  # 넘파이로 ndarray 객체 생성

# a 객체의 형상, 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

# ndim : 배열 축 혹은 차원의 개수를 나타냄
# shape : 배열의 형상을 기술하며 (m, n) 형식의 튜블 형으로 나타냄
# size : 배열 원소의 개수를 말하며 (m, n) 형상 배열의 size는 m X n임
# dtype : 배열 원소의 자료형을 기술함
# itemsize : 배열 원소의 크기를 바이트 단위로 기술. 예를 들어 int32 자료형의 크기는 32/8 = 4바이트
# data : 배열의 실제 원소를 포함하고 있는 버퍼
# stride : 배열의 차원별로 다음 요소로 점프하는 데에 필요한 거리를 바이트로 표시한 값

((3,), 1, dtype('int64'), 8, 3)

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])  # ndarray 객체인 b 생성

b.shape

(2, 3)

In [ ]:
# 다차원 배열은 파이썬 리스트와 유사하게 연산자 적용 가능. 다만 사칙연산 수행 시, 개별 원소별로 연산이 이루어짐.

a = np.array([10, 20, 30]) 
b = np.array([1, 2, 3])

a + b

array([11, 22, 33])

In [ ]:
a - b

array([ 9, 18, 27])

In [ ]:
a * b

array([10, 40, 90])

In [ ]:
a / b

array([10., 10., 10.])

In [ ]:
# 넘파이 배열의 데이터 타입을 지정하는 두 가지 방법

a = np.array([1, 2, 3, 4], dtype = np.int32)  # 속성 값으로 지정
b = np.array([1, 2, 3, 4], dtype = 'int32')  # 문자열 형식으로 속성 값 지정



---



## 3-3. 다차원 배열과 브로드캐스팅

In [ ]:
# 배열에 스칼라 값을 곱하면 모든 원소에 대해 각각 값이 곱해지는 것을 확인 가능

a = np.array([10, 20, 30])
 
a * 10

array([100, 200, 300])

In [ ]:
a + 10

array([20, 30, 40])

브로드캐스팅 : 넘파이는 a * 10을 수행 시, np.array([10, 20, 30]) * np.array([10, 10, 10])와 같이 a의 차원에 맞게 자동으로 스칼라를 벡터로 확장시켜주는 작업을 한다.

벡터화 연산 : 브로드캐스팅과 동시에 파이썬은 하나의 명령을 여러 데이터에 적용하여 병렬적으로 연산한다.

In [ ]:
b = np.array([[10, 20, 30], [40, 50, 60]])
c = np.array([2, 3, 4])

b + c

array([[12, 23, 34],
       [42, 53, 64]])

 또한, 넘파이는 다차원 배열을 쉽게 생성하는 함수도 지원하고 있다.
 zeros((n, m)) 함수는 n X m 배열을 생성하는데 그 초기값은 0으로 한다. ones((n, m)) 함수를 호출하면 초기값을 1로 가지는 n X m 배열을 생성한다.
 
 단위행렬 : 행과 열의 크기가 동일한 정방행렬 중에서 대각선 성분이 1이고 나머지 성분은 0인 행렬이다. eye(n) 함수를 이용해 n X n 크기의 단위행렬을 생성한다.

In [ ]:
np.zeros((2, 3))  # 2행 3열의 행렬 생성, 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))  # 2행 3열의 행렬 생성, 모든 값을 1으로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2, 3), 100)  # 2행 3열의 행렬 생성, 모든 값을 000으로

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(3)  # 3 X 3 크기의 단위행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# ! 도전문제 3.1 : 대각 성분이 모두 10인 4 X 4 크기의 다차원 배열을 생성하기

np.diag([10., 10., 10., 10.])

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])



---

## 3-4. 연속적인 값을 가지는 다차원 배열의 생성


함수 arange(m, n)은 리스트의 range() 함수와 유사하며, m부터 n-1까지 연속적인 정수나 실수를 만들어준다.
 arange(m, n, step)과 같이 3개의 인자을 넣어주게 되면 m부터 n까지 step 만큼 건너뛰며 연속적인 정수나 실수를 생성한다.

In [ ]:
np.arange(0, 10)  # 0에서 9까지 연속적인 수열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)  # 2씩 증가하는 수열을 생성

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0, 10, 3)  # 3씩 증가하는 수열을 생성

array([0, 3, 6, 9])

In [ ]:
np.arange(0.0, 1.0, 0.2)  # 0.2씩 증가하는 수열을 생성

array([0. , 0.2, 0.4, 0.6, 0.8])

linspace() 함수는 지정된 구간에서 동일한 간격의 값을 지정된 횟수만큼 생성한다.
linspace(start, stop, num=50)일때 start~stop 사이의 구간에 대해(start와 stop 값 포함) 50개의 값을 같은 간격으로 생성한다.

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

logspace() 함수는 로스 스케일로 수들을 생성한다. 
logspace(x, y, n)일때 수의 시작은 10^x부너 10^y까지가 되며, n개의 수가 생성된다. 수들 사이의 간격은 로그 스케일로 균등하게 결정된다.

In [ ]:
a = np.logspace(0, 5, 6).round(10)  # 10^0에서 10^5까지 6개의 수를 로그 스케일로 균일한 간격으로 생성한다.
a

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [ ]:
np.log10(a)  # A 배열에 로그를 취하면 0, 1, 2, 3, 4, 5가 생성된다.

array([0., 1., 2., 3., 4., 5.])

In [ ]:
# ? 도전문제 3.2 : sin0도에서 sin180도 사이의 값 11개를 다음과 같이 출력하라. 이때 sin() 함수의 입력을 라디안을 사용하라.

np.linspace(0, np.pi, 11)

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265])



---


## 3-5. 다차원 배열의 축과 삽입


insert() 함수를 이용하여 다차원 배열에서 축을 이용하여 원소를 삽입할 수 있다.

In [ ]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)  # 배열 a의 두 번째 원소에 2를 삽입

array([1, 2, 3, 4])

In [ ]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, 4, axis = 0)  # 배열 b의 axis=0(행) 방향의 두 번째 항목에 4를 삽입한다.

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [ ]:
np.insert(b, 1, 4, axis=1)  # 축의 방향의 두 번째 항목에 4를 삽입한다.

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [ ]:
# 도전문제 3.3 : b 배열에 코드 수행

b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, [1, 2, 3], axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])



---

## 3-6. 파이썬 리스트 VS 넘파이 다차원 배열

파이썬의 리스트는 동일하지 않은 자료형을 가진 항목들을 담을 수 있다. 반면 넘파이의 ndarray 객체는 동일한 자료형의 항목들만 저장한다. 그래서 넘파이가 원소에 접근하는 속도가 더 빠르다.




---

## 3-7. 넘파이 배열의 인덱싱과 슬라이싱

다차원 배열 내의 원소는 인덱스라고 불리는 정수를 사용하여 참조할 수 있다.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 1, 2]])

print(a[0][0])
print(a[2])

1
[7 8 9]


In [ ]:
a[1:][0:2]  # [4, 5], [7, 8], [0, 1]이 값으로 나오지 않는 이유는 a[1:]로 먼저 슬라이싱 하고 그 값을 다시 [0:2]로 슬라이싱 한 값이기 때문이다.

array([[4, 5, 6],
       [7, 8, 9]])



---

## 3-8. 다차원 배열의 최대값, 최소값, 평균값 구하기와 정렬



In [ ]:
a = np.array([10, 20, 30])

# 최대값, 최소값, 평균, 자료형을 float64로 변환
a.max(), a.min(), a.mean(), a.astype(np.float64)

(30, 10, 20.0, array([10., 20., 30.]))

In [ ]:
b = np.array([[1, 1], [2, 2], [3, 3]])

b.flatten()  # 다차원 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

In [ ]:
b.T  # 행과 열의 순서를 서로 교환하는 것(전치)

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
c = np.array([35, 24, 55, 69, 19, 99])

c.sort()  # 배열의 정렬(오름차순)
c[::-1]  # 역순 인덱싱하여 내림차순

array([99, 69, 55, 35, 24, 19])

In [ ]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

d.sort()  # 배열의 정렬. 디폴트는 axis = 1 (행 방향으로 오름차순 정렬)
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [ ]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

d.sort(axis=0)  # 배열의 정렬(열 방향으로 오름차순 정렬)
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

In [ ]:
# 도전문제 3.4 : 내림차순 정렬 연습

d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

d.sort()
np.flip(d, axis=1)

array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

In [ ]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

d.sort(axis=0)
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])



---

## 3-9. 다차원 배열을 위한 append() 함수와 행렬 곱셈

append() 함수는 인자로 입력된 두 배열을 합한다. axis를 통해 축을 명시하지 않으면 디폴트인 1차원 배열로 변환하게 된다.
axis=0과 같이 축을 명시하면 특정한 축으로 합하게 되어 배열의 차원이 유지된다.
두 다차원 배열의 차원이 다르다면 오류를 유발한다.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append([a], b, axis=0)  # [a]를 통해 2차원 배열로 변환해주어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

넘파이에서 제공하는 행렬 곱 함수는 matmul()이다. 이를 더 편하게 사용할 수 있는 것이 @연산자이다.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

a * b  # 2차원 배열의 곱하기 연산 - 원소 간의 곱셈

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
np.matmul(a, b)  # 2차원 배열 a, b의 행렬곱. a @ b라고 쓸 수도 있다.

array([[ 70, 100],
       [150, 220]])

In [ ]:
# 도전문제 3.5 : 다차원 행렬의 생성과 활용

a = np.arange(1, 10).reshape((3, 3))
b = np.full((3, 3), 3)

a + b, a - b, a * b, a / b, a @ b, a ** 2

(array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]), array([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]]), array([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]), array([[0.33333333, 0.66666667, 1.        ],
        [1.33333333, 1.66666667, 2.        ],
        [2.33333333, 2.66666667, 3.        ]]), array([[18, 18, 18],
        [45, 45, 45],
        [72, 72, 72]]), array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]))



---

## 3-10. 과학자들이 사랑하는 수 : 난수

난수란 인간의 의도와 무관하게 생성된 수를 의미하므로, 인간이 만든 기계에 특정 알고리즘을 통해 난수를 생성한다는 것 자체가 모순이다.
하지만 난수와 매우 유사한 특징을 갖는 수를 생성하는 것은 가능하다. 이를 의사 난수라고 한다. 의사난수는 진정한 의미의 난수가 아니지만, 난수와 유사한 기능을 한다.

In [ ]:
def pseudo_rand(x):
  a = 1103515245
  b = 12345
  m = 2 ** 31
  new_x = (a * x + b) % m
  return new_x

seed = 100   # 초기값 임의 설정
x = pseudo_rand(seed)  # seed를 입력으로 하여 새로운 x를 만듦
print(x)
x = pseudo_rand(x)  # x_n을 입력으로 하여 새로운 x_(n + 1)을 만듦
print(x)

829870797
1533044610


난수 생성 코드에는 다음 난수를 생성하기 위한 최초 값이 필요하다. 이를 시드 값이라고 한다. 보통 시드값은 컴퓨터로부터 시간 정보를 얻어와서 사용하는 경우가 많다.

In [ ]:
np.random.randint(150, 191, size=10)  # (최소값, 최대값, 원소의 개수)를 인자로 갖는다.

array([151, 183, 181, 181, 152, 161, 168, 160, 167, 171])



---

## 3-11. 다양한 난수 만들기 함수

넘파이의 난수는 random 서브 모듈에서 제공하는데 randn()함수는 표준 정규 분포를 따르는 난수를 생성하는 데 사용된다.

In [ ]:
rnd = np.random.randn(5) * 10 + 165  # 평균 값이 165, 표준편차가 10인 값 생성. 만약 데이터들이 평균값 165, 표준편차가 10인 정규 분포를 따른다고 할 경우 사용.
rnd

array([154.8315341 , 157.28936784, 167.74036032, 175.25248586,
       165.15039507])

In [ ]:
rnd.round(2)  # 소수점 아래 둘째 자리까지 값으로 변환

array([154.83, 157.29, 167.74, 175.25, 165.15])

In [ ]:
rnd.astype(int)  # 정수형 자료형으로 변환

array([154, 157, 167, 175, 165])

In [ ]:
np.random.seed(42)  # seed를 특정한 값으로 지정하면 매번 동일한 난수의 열을 얻을 수 있다.

In [ ]:
nums = np.random.normal(loc = 165, scale = 10, size = (3, 4)).round(2)  # normal() 함수를 이용해서도 정규 분포를 얻을 수 있다.
nums

array([[167.42, 145.87, 147.75, 159.38],
       [154.87, 168.14, 155.92, 150.88],
       [179.66, 162.74, 165.68, 150.75]])

In [ ]:
a = np.arange(10)  # 0~9값을 생성
np.random.shuffle(a)  # 순서 뒤섞기
a

array([5, 3, 1, 6, 0, 7, 9, 4, 2, 8])

In [ ]:
np.random.permutation([2, 4, 6, 8, 10])

array([10,  6,  4,  8,  2])

In [ ]:
# ! 도전문제 3.6

def train_test_split():
  a = np.arange(1, 51)
  np.random.shuffle(a)
  train_data = a[:40]  # 40 : 10개로 슬라이싱하여 저장함... 퍼센테이지로 슬라이싱 하는 방법은?
  test_data = a[40:]
  return(train_data, test_data)

print(train_test_split())

(array([16,  4, 34, 50, 14,  8, 45, 12, 43, 39,  7, 42, 19,  3, 47, 40, 31,
       46, 21, 11, 48, 15, 32, 26, 22,  1, 24, 23, 37, 41, 49, 38, 30, 10,
        2, 25,  5, 18,  6, 35]), array([44, 29, 28, 13, 20, 33,  9, 17, 27, 36]))




---

## 3-12. 넘파이 스타일의 슬라이싱과 논리 인덱싱

넘파이에서 인덱싱을 이용하여 슬라이싱하면 리스트처럼 슬라이싱 범위가 순차적으로 적용되는 것이 아니라, 각각의 축에 별도로 적용된다.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 1, 2]])
a[1:, 0:2]  # 행 방향으로 1:를 먼저 적용하고 남은 부분에서 0:2를 또 적용

array([[4, 5],
       [7, 8],
       [0, 1]])

넘파이에서는 데이터를 추려내는 데에 슬라이싱 뿐만 아니라 논리 인덱싱이라는 효율적이 방법 또한 제공한다. 이는 특정한 어떤 조건을 주어서 배열에서 원하는 값을 추려내는 것이다.

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a[a % 2 ==0]  # 이렇게 인덱스로 사용하면 해당 조건에 부합하는 원소들만 추출이 가능하다

array([ 2,  4,  6,  8, 10, 12, 14, 16])



---

## 3-13. 넘파이의 성공 이유

배열 프로그래밍은 넘파이의 성공 이유 중 하나이다. 배열 프로그래밍은 데이터에 연산을 실시할 때, 데이터를 구성하는 값 전체에 대해 한 번에 연산이 적용되도록 하는 방식을 의미한다. 이러한 해법을 제공하지 못하는 언어를 스칼라 언어라고 하며, C, C++ 등이 해당된다.

배열 프로그래밍에서 사용하는 연산을 벡터화 연산이라고 한다. 벡터화 연산은 간결하게 코드 표현이 가능하다.
뿐만 아니라 For 반복문을 사용한 스칼라 언어가 각각의 원소들을 순차적으로 처리해야 한다면, 벡터화 연산은 두 배열의 대응하는 원소를 서로 더해서 새로운 배열에 저장하는 일을 차례를 기다리지 않고 동시에 수행할 수 있다. 이렇게 데이터를 잘게 쪼개어 각각에 대해 동일한 연산을 독립적으로 수행하는 방식을 데이터 병렬성이라고 한다.

전통적인 언어로도 데이터 병렬성을 활용할 수 있지만, 벡터화 연산을 그대로 표현하는 효율적인 코딩은 어렵다.
넘파이는 강력하고 압축적인 프로그래밍 구문을 제공하며, 프로그래머가 효율적으로 고성능의 데이터 병렬 처리를 할 수 있게 해준다.



---

## 3-14. 벡터화 연산의 성능 측정

벡터화 연산은 하나의 명령이 여러 데이터에 동시에 적용된 방식으로 배열 프로그래밍의 핵심 요소이다.

In [ ]:
import numpy as np
import time  # 수행시간 측정을 위한 time 모듈

n = 100000
a = np.random.rand(n)  # 난수 100개 생성
b = np.random.rand(n)  # 난수 100개 생성
result = np.zeros(n)  # 0값 100개 채우기

In [ ]:
start = time.time()
for i in range(n):  # C언어 스타일로 명시적 작업 지시
  result[i] = a[i] * b[i]
end = time.time()
print('원소별 접근 방식 소요시간 : ', end - start)

start = time.time()
result = a * b  # 벡터화 연산
end = time.time()
print('벡터화 연산 수행 소요시간 : ', end - start)

원소별 접근 방식 소요시간 :  0.0571897029876709
벡터화 연산 수행 소요시간 :  0.0008554458618164062


벡터화 연산을 사용한 것이 훨씬 연산이 빠르다는 것을 알 수 있다.



---

## 3-15. 리덕션 : 배열을 더 강력하게 만드는 기능

넘파이의 다차원 배열은 리덕션이라는 기능을 제공한다. 리덕션이란 여러 개의 수로 이루어진 배열을 하나의 수로 집계하는 것이다.

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(np.sum(a, axis=0))  # 열끼리 더함
print(np.sum(a, axis=1))  # 행끼리 더함
print(np.sum(a, axis=(0, 1)))  # 모두 더함(생략 가능)

[ 5 10 15 20 25]
[15 15 15 15 15]
75




---

## 3-16. 선형방정식을 풀어보자

넘파이의 linalg라는 서브 모듈을 이용하여 선형대수, 벡터의 내적과 외적, 크로네커 곱, 행렬 분해, 노름, 행렬, 랭크 등을 구하기 위한 다양한 함수를 사용할 수 있다.

In [ ]:
# x + 2y = 6
# x - 3y = 1     이라는 선형 연립 방정식이 있을 때 해 구하기

a = np.array([[1, 2], [1, -3]])
b = np.array([6, 1])
s = np.linalg.solve(a, b)
print(s)

[4. 1.]


연립 방정식이 해를 가지는 경우도 있지만 그렇지 않은 경우도 있다. 이를 판별하기 위해서는 행렬식을 사용한다.
행렬식은 정방 행렬에 수를 대응시키는 함수이다.

In [ ]:
a = np.array([[2, 1], [4, 5]])
det_a = np.linalg.det(a)  # a 행렬의 행렬식
b = np.array([[1, 2], [3, -6]])
det_b = np.linalg.det(b)  # b 행렬의 행렬식
print(det_a, det_b)

6.0 -12.0


In [ ]:
# ? 도전문제 3.7 : 다차원 행렬의 생성과 활용





---

## 3-17. 배열의 결합

In [ ]:
a = np.arange(10, 18).reshape(2, 4)
b = np.arange(12).reshape(3, 4)
c = np.arange(8).reshape(2, 4)
d = list(range(4))
print(a)  # (2, 4) 형상의 다차원 배열로 10~17의 원소를 가짐
print(b)  # (3, 4) 형상의 다차원 배열로10~11의 원소를 가짐
print(c)  # (2, 4) 형상의 다차원 배열로 0~7의 원소를 가짐
print(d)  # 1차원 리스트로 0~3의 원소를 가짐

[[10 11 12 13]
 [14 15 16 17]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
[0, 1, 2, 3]


리스트를 결합하기 위해서는 + 연산자를 사용할 수 있으나 다차원 배열의 +는 두 배열의 원소의 합이 되므로 대신 넘파이의 concatenate() 함수를 사용해 두 리스트를 결합할 수 있다.

In [ ]:
np.concatenate((a, b))  # a 배열의 마지막 원소 뒤에 b 배열을 넣는다.

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.vstack((a, b))  # a 배열과 b 배열을 수직 방향으로 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.vstack((a, d))  # a 배열과 d 리스트의 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [ ]:
np.vstack((a, b, d))  # 다차원 배열 3개를 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [ ]:
np.hstack((a, c))  # 다차원 배열 a, c를 수형으로 결합. hstak은 axis 0의 차원값이 동일한 때에만 결합
# np.hstack((a, b))  # 형상이 달라 오류

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])



---

## 3-18. 배열을 결합하는 r_, c_ 클래스와 column_stack() 함수


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
np.r_[a, b]  # a, b 배열을 결합. np.hstack([a, b])와 같음

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.r_[a, 4, 5, 6, b]  # 중간에 개별 원소 삽입도 가능

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [ ]:
np.r_[[0] * 3, 5, 6]

array([0, 0, 0, 5, 6])

In [ ]:
np.r_[c, d]  # 2차원 배열을 axis = 0 방향으로 결합

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.r_[a.reshape(-1, 1), b.reshape(-1, 1)]  # a, b를 2차원 배열로 만들어서 axis=0 방향으로 결합

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [20],
       [30]])

In [ ]:
np.concatenate((a.reshape(-1, 1), b.reshape(-1, 1)), axis=1)  # a, b의 각 원소끼리 묶어 다차원 배열을 만든다

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.c_[a, b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.column_stack([a, b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.concatenate((c.T, d.T), axis=1)  # c와 d의 전치행렬을 결합시킨다

array([[ 1,  4, 10, 40],
       [ 2,  5, 20, 50],
       [ 3,  6, 30, 60]])